### ISSUE TITLE
能用在mapbox、cesium等框架上吗

### ISSUE THREAD

**Issue by wilsunson** [bojue/BaseMap#2]
比如用baseMap画好底图，然后通过添加高度方式，生成2.5d或3d地图那样的数据

**Comment by bojue** [comment]
@wilsunson

这个问题目前不支持

这个需求我们是解决3d开发效率和2.5D成本的问题，你说的这个场景不支持，我们之前是其他同事基于threejsEditor开发3d编辑器解决的，开发成本有点高

baseMap可以保存位置和元素类型信息，理论上可以通过转换数据格式3d地图
