### ISSUE TITLE
【迭代建议】希望有vue3 + ts 版本的

### ISSUE THREAD

**Issue by ElsaOOo** [bojue/BaseMap#3]
希望有vue3 + ts 版本的

**Comment by bojue** [comment]
@ElsaOOo  这个项目是给公司UI和客户开发的一个工具，因为离开IDC行业了所以开源处理给需要的人，Vue当时主流是2.0版本所以直接看文档开发了，后期如果新的开源项目会考虑React+TS+Webpack+Vite这个方案
