### ISSUE TITLE
页面滚动问题

### ISSUE THREAD

**Issue by MakinoharaShoko** [bojue/BaseMap#7]
希望可以设置组件库列表单独滚动，不要影响整个页面（因为我只是想要滚动组件库找到需要的组件，但是不想整个页面因此滚动，妨碍到编辑画布）

**Comment by bojue** [comment]
@MakinoharaShoko 好的，5月底前处理一下这个问题

**Comment by bojue** [comment]
@MakinoharaShoko 已经修复
